language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t antonwibowo/complex-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true antonwibowo/complex-test npm test 

after_success:
  - docker build -t antonwibowo/tut-multi-client ./client
  - docker build -t antonwibowo/tut-multi-nginx ./nginx
  - docker build -t antonwibowo/tut-multi-server ./server
  - docker build -t antonwibowo/tut-multi-worker ./worker
  # Log in to CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push to Dockerhub
  - docker push antonwibowo/tut-multi-client
  - docker push antonwibowo/tut-multi-nginx
  - docker push antonwibowo/tut-multi-server
  - docker push antonwibowo/tut-multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: ap-southeast-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-ap-southeast-1-731423952287
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY