language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t antonwibowo/complex-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true antonwibowo/complex-test npm test 

after_success:
  - docker build -t antonwibowo/tut-multi-client ./client
  - docker build -t antonwibowo/tut-multi-nginx ./nginx
  - docker build -t antonwibowo/tut-multi-server ./server
  - docker build -t antonwibowo/tut-multi-worker ./worker
  # Log in to CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push to Dockerhub
  - docker push antonwibowo/tut-multi-client
  - docker push antonwibowo/tut-multi-nginx
  - docker push antonwibowo/tut-multi-server
  - docker push antonwibowo/tut-multi-worker